"""
Pydantic Schemas for Structured LLM Outputs.
Guarantees strict JSON schema conformance for question generation,
answer evaluation, and targeted follow-up probing.
"""
from typing import List, Optional
from pydantic import BaseModel, Field


class LLMEvaluationOutput(BaseModel):
    """Structured 4-Dimensional evaluation returned by LLM assessor."""
    correctness: float = Field(..., ge=0.0, le=100.0, description="Core factual accuracy score 0-100")
    depth: float = Field(..., ge=0.0, le=100.0, description="Underlying mechanics and theoretical depth score 0-100")
    tradeoff_awareness: float = Field(..., ge=0.0, le=100.0, description="Awareness of trade-offs, bottlenecks, and alternatives 0-100")
    real_world_applicability: float = Field(..., ge=0.0, le=100.0, description="Application to realistic production scenarios/edge cases 0-100")
    strengths: List[str] = Field(default_factory=list, description="Key concepts correctly articulated by the student")
    weaknesses: List[str] = Field(default_factory=list, description="Specific conceptual flaws, vague points, or misconceptions")
    missing_concepts: List[str] = Field(default_factory=list, description="Concrete sub-concepts or trade-offs omitted in the answer")
    reasoning: str = Field(..., description="Detailed diagnostic rationale for the dimensional scores")


class LLMQuestionOutput(BaseModel):
    """Structured question generated by LLM considering prerequisites and past weaknesses."""
    question: str = Field(..., description="The adaptive opening question text")
    focus_concept: str = Field(..., description="The primary concept being targeted")
    expected_depth_areas: List[str] = Field(default_factory=list, description="Key areas the student should cover in a complete answer")


class LLMFollowUpOutput(BaseModel):
    """Structured follow-up probe generated from the student's identified missing concepts."""
    follow_up_question: str = Field(..., description="Targeted follow-up probing question")
    targeted_missing_concept: str = Field(..., description="The exact missing concept being probed")
    rationale: str = Field(..., description="Why this follow-up was selected based on the student's previous answer")
